/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsVrStoreRouteImport } from './routes/projects.vr-store'
import { Route as ProjectsHRadheRouteImport } from './routes/projects.h-radhe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsVrStoreRoute = ProjectsVrStoreRouteImport.update({
  id: '/projects/vr-store',
  path: '/projects/vr-store',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsHRadheRoute = ProjectsHRadheRouteImport.update({
  id: '/projects/h-radhe',
  path: '/projects/h-radhe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/h-radhe': typeof ProjectsHRadheRoute
  '/projects/vr-store': typeof ProjectsVrStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/h-radhe': typeof ProjectsHRadheRoute
  '/projects/vr-store': typeof ProjectsVrStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/h-radhe': typeof ProjectsHRadheRoute
  '/projects/vr-store': typeof ProjectsVrStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/h-radhe' | '/projects/vr-store'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/h-radhe' | '/projects/vr-store'
  id: '__root__' | '/' | '/projects/h-radhe' | '/projects/vr-store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsHRadheRoute: typeof ProjectsHRadheRoute
  ProjectsVrStoreRoute: typeof ProjectsVrStoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/vr-store': {
      id: '/projects/vr-store'
      path: '/projects/vr-store'
      fullPath: '/projects/vr-store'
      preLoaderRoute: typeof ProjectsVrStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/h-radhe': {
      id: '/projects/h-radhe'
      path: '/projects/h-radhe'
      fullPath: '/projects/h-radhe'
      preLoaderRoute: typeof ProjectsHRadheRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsHRadheRoute: ProjectsHRadheRoute,
  ProjectsVrStoreRoute: ProjectsVrStoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
